// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1) {
  return window['go']['player']['Player']['OpenFile'](arg1);
}

export function PlayerChangeVolume(arg1) {
  return window['go']['player']['Player']['PlayerChangeVolume'](arg1);
}

export function PlayerPause() {
  return window['go']['player']['Player']['PlayerPause']();
}

export function PlayerResume() {
  return window['go']['player']['Player']['PlayerResume']();
}

export function PlayerToggleMute(arg1) {
  return window['go']['player']['Player']['PlayerToggleMute'](arg1);
}

export function Startup(arg1) {
  return window['go']['player']['Player']['Startup'](arg1);
}
