// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { context } from '../models'

export function OpenFile(arg1: string): Promise<string>

export function PlayerChangeVolume(arg1: number): Promise<void>

export function PlayerPause(): Promise<void>

export function PlayerResume(): Promise<void>

export function PlayerToggleMute(arg1: boolean): Promise<void>

export function Startup(arg1: context.Context): Promise<void>
