// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bluetooth} from '../models';

export function ConnectToDevice(arg1:string):Promise<boolean>;

export function GetConnectedDevice():Promise<bluetooth.bluetoothDevice>;

export function GetDeviceList():Promise<Array<bluetooth.bluetoothDevice>>;
