// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDevice(arg1) {
  return window['go']['bluetooth']['Bluetooth']['ConnectToDevice'](arg1);
}

export function GetConnectedDevice() {
  return window['go']['bluetooth']['Bluetooth']['GetConnectedDevice']();
}

export function GetDeviceList() {
  return window['go']['bluetooth']['Bluetooth']['GetDeviceList']();
}
